all:
  exclude:
    - 'spec/**/*'
# exclude files for single runner
eslint:
  exclude:
    - 'app/assets/**/*'
github:
  slug: juanfer2/derose
  access_token: ${PRONTO_GITHUB_ACCESS_TOKEN}
  api_endpoint: https://api.github.com/
  web_endpoint: https://github.com/
max_warnings: 150
warnings_per_review: 30
verbose: false
